import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface ExportOptions {
  title: string;
  content: string;
  drawings: string[];
  element?: HTMLElement;
}

export async function exportToPDF({ title, content, drawings, element }: ExportOptions): Promise<void> {
  try {
    // Create a temporary container for export
    const exportContainer = document.createElement('div');
    exportContainer.style.cssText = `
      position: absolute;
      left: -9999px;
      top: -9999px;
      width: 210mm;
      padding: 20px;
      background: white;
      font-family: 'Inter', sans-serif;
      line-height: 1.6;
    `;

    // Add title
    const titleElement = document.createElement('h1');
    titleElement.textContent = title || 'Untitled Note';
    titleElement.style.cssText = `
      font-size: 24px;
      font-weight: bold;
      margin-bottom: 20px;
      color: #1a1a1a;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 10px;
    `;
    exportContainer.appendChild(titleElement);

    // Add content (sanitized to prevent XSS)
    const contentElement = document.createElement('div');
    // Sanitize HTML content before rendering
    const sanitizedContent = content
      .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
      .replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, '')
      .replace(/on\w+="[^"]*"/gi, '')
      .replace(/javascript:/gi, '');
    contentElement.innerHTML = sanitizedContent;
    contentElement.style.cssText = `
      margin-bottom: 30px;
      font-size: 14px;
      color: #374151;
    `;
    exportContainer.appendChild(contentElement);

    // Add drawings if any
    if (drawings.length > 0) {
      const drawingsSection = document.createElement('div');
      drawingsSection.style.cssText = `
        margin-top: 30px;
        padding-top: 20px;
        border-top: 1px solid #e5e7eb;
      `;

      const drawingsTitle = document.createElement('h2');
      drawingsTitle.textContent = 'Drawings';
      drawingsTitle.style.cssText = `
        font-size: 18px;
        font-weight: bold;
        margin-bottom: 15px;
        color: #1a1a1a;
      `;
      drawingsSection.appendChild(drawingsTitle);

      drawings.forEach((drawing, index) => {
        const drawingContainer = document.createElement('div');
        drawingContainer.style.cssText = `
          margin-bottom: 20px;
          page-break-inside: avoid;
        `;

        const drawingLabel = document.createElement('p');
        drawingLabel.textContent = `Drawing ${index + 1}`;
        drawingLabel.style.cssText = `
          font-size: 12px;
          color: #6b7280;
          margin-bottom: 8px;
          font-style: italic;
        `;
        drawingContainer.appendChild(drawingLabel);

        const img = document.createElement('img');
        img.src = drawing;
        img.style.cssText = `
          max-width: 100%;
          height: auto;
          border-radius: 8px;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        `;
        drawingContainer.appendChild(img);
        drawingsSection.appendChild(drawingContainer);
      });

      exportContainer.appendChild(drawingsSection);
    }

    // Add footer
    const footer = document.createElement('div');
    footer.style.cssText = `
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      font-size: 12px;
      color: #6b7280;
      text-align: center;
    `;
    footer.innerHTML = `
      <p>Generated by FunFinity Academy Notes</p>
      <p>${new Date().toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      })}</p>
    `;
    exportContainer.appendChild(footer);

    // Temporarily add to DOM for rendering
    document.body.appendChild(exportContainer);

    // Create canvas from the container
    const canvas = await html2canvas(exportContainer, {
      scale: 2, // Higher resolution
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      width: 794, // A4 width in pixels at 96 DPI
      windowWidth: 794,
    });

    // Remove temporary container
    document.body.removeChild(exportContainer);

    // Create PDF
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 0;

    // Add image to PDF, handling multi-page content
    while (heightLeft >= 0) {
      pdf.addImage(
        imgData,
        'PNG',
        0,
        position,
        imgWidth,
        Math.min(imgHeight, pageHeight)
      );
      heightLeft -= pageHeight;
      position -= pageHeight;
      
      if (heightLeft > 0) {
        pdf.addPage();
      }
    }

    // Add metadata
    pdf.setProperties({
      title: title || 'Note',
      subject: 'Study Notes',
      author: 'FunFinity Academy',
      keywords: 'notes, study, education',
      creator: 'FunFinity Academy Notes System'
    });

    // Save the PDF
    const fileName = `${(title || 'note').replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.pdf`;
    pdf.save(fileName);

  } catch (error) {
    console.error('Error exporting PDF:', error);
    throw new Error('Failed to export PDF. Please try again.');
  }
}

export async function exportToSimplePDF({ title, content }: Omit<ExportOptions, 'drawings' | 'element'>): Promise<void> {
  try {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    // Add title
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.text(title || 'Untitled Note', 20, 30);

    // Add content (strip HTML and convert to plain text)
    const tempDiv = document.createElement('div');
    // Sanitize HTML content before rendering
    const sanitizedContent = content
      .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
      .replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, '')
      .replace(/on\w+="[^"]*"/gi, '')
      .replace(/javascript:/gi, '');
    tempDiv.innerHTML = sanitizedContent;
    const plainText = tempDiv.textContent || tempDiv.innerText || '';
    
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    
    const lines = pdf.splitTextToSize(plainText, 170); // 170mm width
    let yPosition = 50;
    
    lines.forEach((line) => {
      if (yPosition > 270) { // Near bottom of page
        pdf.addPage();
        yPosition = 30;
      }
      pdf.text(line, 20, yPosition);
      yPosition += 7;
    });

    // Add footer
    pdf.setFontSize(10);
    pdf.text('Generated by FunFinity Academy Notes', 20, 280);
    pdf.text(new Date().toLocaleDateString(), 20, 285);

    // Save the PDF
    const fileName = `${(title || 'note').replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.pdf`;
    pdf.save(fileName);

  } catch (error) {
    console.error('Error exporting simple PDF:', error);
    throw new Error('Failed to export PDF. Please try again.');
  }
}
